name = "whats-in-my-fridge"

compatibility_date = "2023-07-01"

send_metrics = false
pages_build_output_dir = "dist"

[dev]
local_protocol = "https"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "SYNC_TOKEN"
id = "df7eefa49b86403e849c3ad270620e9f"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#r2-buckets
[[r2_buckets]]
binding = "SYNC_BUCKET"
bucket_name = "whats-in-my-fridge-sync"
